var discord = require('discord.js')

exports.run = (client, message, args) => {
    var embed = new discord.RichEmbed()
        .setAuthor(message.author.username, message.author.DisplayAvatarURL)
        .setColor("#FFBF00")
        .setDescription("Página principal dos comandos de DogeBot!! \n Se divirtam com jogos e memes de DogeBot,um Bot ainda em fase de teste mas que planeja ter um grande potencial!! \n OBRIGADO PELA PREFERENCIA.")
        .setTitle("☆INICIO☆ DogeBot <:alan4:401078774042591242> \n┗(＾∀＾)┛")
        .setURL()
        .setTimestamp()
        .setImage("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeaUkNiDxcKE8xR9kJWc609xFOjMrqiKZHgjrasIl01Y91R3kp")
        .setFooter(client.user.username)
        .setThumbnail(client.user.avatarURL)
        .addField ()
         message.author.send(embed)
            var embed = new discord.RichEmbed()
                .setAuthor(message.author.username)
                .setColor("#FFBF00")
                .setDescription("Uma ajuda para quem não tem conhecimentos sobre os comandos de DogeBot.Ainda em fase experimental....")
                .setTitle("☆Página 1☆ DogeBot  <:alan4:401078774042591242>" )
                .setURL()
                .setTimestamp()
                .setImage()
                .setFooter(client.user.username)
                .setThumbnail(client.user.avatarURL)
                .addField("☆BOTS SIMPLES PÁGINA 1","\n ☆COMANDOS:\n n.ban <menção>\n n.Kamehameha <menção>\n n.ping \n n.jooj <menção> \n n.ppt (PEDRA,PAPEL OU TESOURA) ainda em desenvolvimento ... \n n.advinha <pergunta>" )
                 message.author.send(embed)
                    var embed = new discord.RichEmbed()
                        .setAuthor(message.author.username)
                        .setColor("#FFBF00")
                        .setDescription("")
                        .setTitle("☆Página 2☆ DogeBot  <:alan4:401078774042591242>")
                        .setURL()
                        .setTimestamp()
                        .setImage()
                        .setFooter(client.user.username)
                        .setThumbnail(client.user.avatarURL)
                        .addField("☆BOTS SIMPLES PÁGINA 2","\n ☆COMANDOS: \n n.abraco <menção> \n n.dado" )
                         message.author.send(embed)
                    }
            
    
